FROM loukordos/biped-sim-base-image:develop

ENV LD_LIBRARY_PATH /src/control_plugin/build

ENV IS_DOCKER Y

COPY . /src
COPY . /root/.gazebo/models/simplified_biped

WORKDIR /src/control_plugin

RUN rm -rf ./build && mkdir ./build
WORKDIR /src/control_plugin/build

RUN cmake ..
RUN make -j$(nproc)

# Current command: sudo docker run -it --gpus all --net=host -e "TERM=xterm-256color" --env="DISPLAY" --volume="$HOME/.Xauthority:/root/.Xauthority:rw" loukordos/biped-sim